### ISSUE TITLE
Visualization in demo.py

### ISSUE THREAD

**Issue by jakeoung** [tenstep/DeepModel#10]
Hello, I have a question in `demo.py`. I saw the following code.

```
      for j in range(J):
        x[j] = joint[joints[j] * 3]
        y[j] = joint[joints[j] * 3 + 1]   
        z[j] = joint[joints[j] * 3 + 2]
        cv2.circle(img, (int((x[j] + 1) / 2 * 128), int((- y[j] + 1) / 2 * 128)), 2, (255, 0, 0), 2)
```

After computing the joint in 3D, it seems that we just normalize x,y coordinates to [0,128). I reimplement your code to run pytorch, my output for the **ground truth** (not my prediction of network) is like this:

![image](https://cloud.githubusercontent.com/assets/2376897/25369762/388e2d9c-29c1-11e7-9d65-21de9f222a35.png)

The joints looks wrong and should be positioned left slightly. I wonder that it is normal or not (due to cropping, reisize and so on..)

**Comment by xingyizhou** [comment]
Hi jakeoung, 
  Sorry for the late reply. You are right, it is normal. It is because I use a simple version (weak perspective projection) to project the 2D joint for visualization. It should be perspective projection (u[i] ~ x[i] / z[i], v[i] ~ y[i] / z[i]), not (u[i] ~ x[i], v[i] ~ y[i]). If you want to plot the 2D joint strictly, you should also consider the x and y focal length of the camera to convert the xyz space to uvd space (you can refer to the official converting code in NYU hand pose dataset).
