### ISSUE TITLE
error in caffe while building layer deephandmodel

### ISSUE THREAD

**Issue by shomedas** [tenstep/DeepModel#3]
I0614 12:48:35.391320 30215 layer_factory.hpp:77] Creating layer DeepHandModel
I0614 12:48:35.391338 30215 net.cpp:91] Creating Layer DeepHandModel
I0614 12:48:35.391347 30215 net.cpp:425] DeepHandModel <- DoF
I0614 12:48:35.391356 30215 net.cpp:399] DeepHandModel -> DeepHandModelxyz
**\* Aborted at 1465888715 (unix time) try "date -d @1465888715" if you are using GNU date ***
PC: @     0x7f9b7cc44754 (unknown)
**\* SIGSEGV (@0xc0) received by PID 30215 (TID 0x7f9b7ee55780) from PID 192; stack trace: ***
    @     0x7f9b7cc26d40 (unknown)
    @     0x7f9b7cc44754 (unknown)
    @     0x7f9b7cc4d147 (unknown)
    @     0x7f9b7e670cd9 caffe::DeepHandModelLayer<>::LayerSetUp()
    @     0x7f9b7e6f0515 caffe::Net<>::Init()
    @     0x7f9b7e6f13b5 caffe::Net<>::Net()
    @     0x7f9b7e67b72a caffe::Solver<>::InitTrainNet()
    @     0x7f9b7e67c93c caffe::Solver<>::Init()
    @     0x7f9b7e67cc6a caffe::Solver<>::Solver()
    @     0x7f9b7e6d43e3 caffe::Creator_SGDSolver<>()
    @           0x411666 caffe::SolverRegistry<>::CreateSolver()
    @           0x40ab20 train()
    @           0x40852c main
    @     0x7f9b7cc11ec5 (unknown)
    @           0x408cfd (unknown)
    @                0x0 (unknown)
Segmentation fault

caffe installation tests ran ok. hdf5_classification example also ran ok. Why is this(DeepHandModel) failing? Did you encounter this error? How did you fix it?

**Comment by strawberryfg** [comment]
I remember I once encountered this problem. The problem is most likely caused by failing to read configuration files. That is to say, LayerSetUp function of DeepHandModelLayer reads bone length, index of constrained DoF, lower/upper bound of each DoF, initial motion parameters(seed hand pose) from the six 'txt' at the relative path 'configuration/'.

You may create a folder called 'configuration' where you execute caffe training and copy six files from github path: DeepModel/training/configuration/ to this folder.

I'm not 100% sure if it can solve the problem. 
Thanks for your attention!
